name: CI

# El pipeline se DISPARA solo con cada push y cada pull request.
on:
  push:
  pull_request:

jobs:
  construir-y-probar:
    runs-on: ubuntu-lastest
    steps:
      - name: Traer el codigo
        uses: actions/checkout@v4

      - name: Preparar Javav 26
        uses: actions/set-upjava@v4
        with:
          distribution: temurin
          java-version: '26'
          cache: maven

      - name: Compilar y PROBAR
        run: mvn -B verify

      - name: Construir la imagen
        run: docker build -t ejemplo:${{ github.sha }}